services:
  proxy:
    image: shodon2007/networth-proxy:latest
    container_name: networth-proxy
    env_file:
      - ./networth-proxy/.env
    ports:
      - 80:80
      - 3000:3000
    depends_on:
      - client
    networks:
      - back
      - front
  client:
    image: shodon2007/networth-client:latest
    container_name: networth-client
    depends_on:
      - api
    networks:
      - front
  api:
    image: shodon2007/networth-api:latest
    container_name: networth-api
    env_file:
      - ./networth-api/.env
    depends_on:
      db:
        condition: service_healthy
        restart: true
      search:
        condition: service_healthy
        restart: true
    networks:
      - db
      - back
      - search
  db:
    image: shodon2007/networth-db:latest
    container_name: networth-db
    env_file:
      - ./networth-db/.env
    ports:
      - 3307:3306
    volumes:
      - ./networth-db/data:/var/lib/mysql
      - ./networth-db/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - db
  search:
    image: shodon2007/networth-search
    container_name: networth-search
    ports:
      - 7700:7700
    healthcheck:
      test: curl -X GET 'http://localhost:7700/health'
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s
    volumes:
      - ./networth-search/meili_data:/meili_data
    env_file:
      - ./networth-search/.env
    networks:
      - search

networks:
  front:
    driver: bridge
  back:
    driver: bridge
  db:
    driver: bridge
  search:
    driver: bridge
